<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Neraca;

class NeracaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $neraca = [
            [
                'id' => '1',
                'periode' => '2018',
                'kode_akun' => '1-1100.000',
                'nama_akun' => 'Kas',
                'nominal' => 10871057,
            ],
            [
                'id' => '2',
                'periode' => '2018',
                'kode_akun' => '1-1200.000',
                'nama_akun' => 'Bank',
                'nominal' => 7581265405,
            ]
            // ,
            // [
            //     'id' => '3',
            //     'periode' => '2018',
            //     'kode_akun' => '1-1300.000',
            //     'nama_akun' => 'Piutang Dagang',
            //     'nominal' => 58115665111,
            // ],
            // [
            //     'id' => '4',
            //     'periode' => '2018',
            //     'kode_akun' => '1-1400.000',
            //     'nama_akun' => 'Piutang Karyawan',
            //     'nominal' => 54146420,
            // ],
            // [
            //     'id' => '5',
            //     'periode' => '2018',
            //     'kode_akun' => '1-1500.000',
            //     'nama_akun' => 'Piutang Lain-lain',
            //     'nominal' => 17239832237,
            // ],
            // [
            //     'id' => '6',
            //     'periode' => '2018',
            //     'kode_akun' => '1-1600.000',
            //     'nama_akun' => 'Piutang Pemegang Saham',
            //     'nominal' => 17357499316,
            // ],
            // [
            //     'id' => '7',
            //     'periode' => '2018',
            //     'kode_akun' => '1-1700.000',
            //     'nama_akun' => 'Persediaan Barang',
            //     'nominal' => 6188127867,
            // ],
            // [
            //     'id' => '8',
            //     'periode' => '2018',
            //     'kode_akun' => '1-1800.000',
            //     'nama_akun' => 'Uang Muka & Biaya Dibayar Dimuka',
            //     'nominal' => 344178511,
            // ],
            // [
            //     'id' => '9',
            //     'periode' => '2018',
            //     'kode_akun' => '1-1900.000',
            //     'nama_akun' => 'Pajak Dibayar Dimuka',
            //     'nominal' => 0,
            // ],
            // [
            //     'id' => '10',
            //     'periode' => '2018',
            //     'kode_akun' => '1-2100.000',
            //     'nama_akun' => 'Tanah',
            //     'nominal' => 55314139561,
            // ],
            // [
            //     'id' => '11',
            //     'periode' => '2018',
            //     'kode_akun' => '1-2200.000',
            //     'nama_akun' => 'Bangunan',
            //     'nominal' => 25087147669,
            // ],
            // [
            //     'id' => '12',
            //     'periode' => '2018',
            //     'kode_akun' => '1-2300.000',
            //     'nama_akun' => 'Mesin, Peralatan & Perlengkapan',
            //     'nominal' => 72843273026,
            // ],
            // [
            //     'id' => '13',
            //     'periode' => '2018',
            //     'kode_akun' => '1-2400.000',
            //     'nama_akun' => 'Kendaraan',
            //     'nominal' => 9945813857,
            // ],
            // [
            //     'id' => '14',
            //     'periode' => '2018',
            //     'kode_akun' => '1-2500.000',
            //     'nama_akun' => 'Inventaris Kantor',
            //     'nominal' => 2461562808,
            // ],
            // [
            //     'id' => '15',
            //     'periode' => '2018',
            //     'kode_akun' => '1-3100.000',
            //     'nama_akun' => 'Akum. Penyusutan Bangunan',
            //     'nominal' => -6612945420,
            // ],
            // [
            //     'id' => '16',
            //     'periode' => '2018',
            //     'kode_akun' => '1-3200.000',
            //     'nama_akun' => 'Akum. Penyusutan Mesin, Peralatan & Perlengkapan',
            //     'nominal' => -57334227613,
            // ],
            // [
            //     'id' => '17',
            //     'periode' => '2018',
            //     'kode_akun' => '1-3300.000',
            //     'nama_akun' => 'Akum. Penyusutan Kendaraan',
            //     'nominal' => -8401146035,
            // ],
            // [
            //     'id' => '18',
            //     'periode' => '2018',
            //     'kode_akun' => '1-3400.000',
            //     'nama_akun' => 'Akum. Penyusutan Inventaris Kantor',
            //     'nominal' => -2369991898,
            // ],
            // [
            //     'id' => '19',
            //     'periode' => '2018',
            //     'kode_akun' => '1-4100.000',
            //     'nama_akun' => 'Pajak Tangguhan',
            //     'nominal' => 11341409061,
            // ],
            // [
            //     'id' => '20',
            //     'periode' => '2018',
            //     'kode_akun' => '1-4200.000',
            //     'nama_akun' => 'Investasi PT.Lain',
            //     'nominal' => 38764110000,
            // ],
            // // batas 20 baris
            // [
            //     'id' => '21',
            //     'periode' => '2018',
            //     'kode_akun' => '2-1100.000',
            //     'nama_akun' => 'Hutang Dagang',
            //     'nominal' => 47841700537,
            // ],
            // [
            //     'id' => '22',
            //     'periode' => '2018',
            //     'kode_akun' => '2-1200.000',
            //     'nama_akun' => 'Hutang Komisi Penjualan',
            //     'nominal' => 1155238969,
            // ],
            // [
            //     'id' => '23',
            //     'periode' => '2018',
            //     'kode_akun' => '2-1300.000',
            //     'nama_akun' => 'Hutang Lain-lain',
            //     'nominal' => 789620000,
            // ],
            // [
            //     'id' => '24',
            //     'periode' => '2018',
            //     'kode_akun' => '2-1400.000',
            //     'nama_akun' => 'Hutang Bank Jangka Pendek',
            //     'nominal' => 40438471945,
            // ],
            // [
            //     'id' => '25',
            //     'periode' => '2018',
            //     'kode_akun' => '501',
            //     'nama_akun' => 'Pendapatan Penjualan',
            //     'nominal' => 20000000,
            // ],
            // [
            //     'id' => '26',
            //     'periode' => '2018',
            //     'kode_akun' => '2-1500.000',
            //     'nama_akun' => 'Hutang Pajak',
            //     'nominal' => 277083128,
            // ],
            // [
            //     'id' => '27',
            //     'periode' => '2018',
            //     'kode_akun' => '2-1600.000',
            //     'nama_akun' => 'Liabilitas Pembiayaan Konsumen Jangka Pendek',
            //     'nominal' => 344781283,
            // ],
            // [
            //     'id' => '28',
            //     'periode' => '2018',
            //     'kode_akun' => '2-1700.000',
            //     'nama_akun' => 'Hutang Mesin',
            //     'nominal' => 690656753,
            // ],
            // [
            //     'id' => '29',
            //     'periode' => '2018',
            //     'kode_akun' => '2-1800.000',
            //     'nama_akun' => 'Uang Muka Penjualan',
            //     'nominal' => 0,
            // ],
            // [
            //     'id' => '30',
            //     'periode' => '2018',
            //     'kode_akun' => '2-1900.000',
            //     'nama_akun' => 'Biaya yang masih harus dibayar',
            //     'nominal' => 3006526532,
            // ],
            // [
            //     'id' => '31',
            //     'periode' => '2018',
            //     'kode_akun' => '2-2000.000',
            //     'nama_akun' => 'Hutang Kepada Pemegang Saham',
            //     'nominal' => 21445619441,
            // ],
            // [
            //     'id' => '32',
            //     'periode' => '2018',
            //     'kode_akun' => '2-2100.000',
            //     'nama_akun' => 'Hutang Bank Jangka Panjang',
            //     'nominal' => 83280084541,
            // ],
            // [
            //     'id' => '33',
            //     'periode' => '2018',
            //     'kode_akun' => '2-2200.000',
            //     'nama_akun' => 'Liabilitas Pembiayaan Konsumen Jangka Panjang',
            //     'nominal' => 1199581733,
            // ],
            // [
            //     'id' => '34',
            //     'periode' => '2018',
            //     'kode_akun' => '2-2300.000',
            //     'nama_akun' => 'Liabilitas Imbalan Kerja',
            //     'nominal' => 11329377018,
            // ],
            // [
            //     'id' => '35',
            //     'periode' => '2018',
            //     'kode_akun' => '3-1100.000',
            //     'nama_akun' => 'Modal Disetor',
            //     'nominal' => 2500000000,
            // ],
            // [
            //     'id' => '36',
            //     'periode' => '2018',
            //     'kode_akun' => '3-1200.000',
            //     'nama_akun' => 'Uang Muka Setoran Modal',
            //     'nominal' => 0,
            // ],
            // [
            //     'id' => '37',
            //     'periode' => '2018',
            //     'kode_akun' => '3-1300.000',
            //     'nama_akun' => 'Surplus Revaluasi Tanah',
            //     'nominal' => 10700961900,
            // ],
            // [
            //     'id' => '38',
            //     'periode' => '2018',
            //     'kode_akun' => '3-1400.000',
            //     'nama_akun' => 'Tax Amnesty',
            //     'nominal' => 1620000000,
            // ],
            // [
            //     'id' => '39',
            //     'periode' => '2018',
            //     'kode_akun' => '3-1500.000',
            //     'nama_akun' => 'Laba Ditahan',
            //     'nominal' => 4750000000,
            // ],
            // [
            //     'id' => '40',
            //     'periode' => '2018',
            //     'kode_akun' => '3-1600.000',
            //     'nama_akun' => 'Deviden',
            //     'nominal' => 0,
            // ],
            // [
            //     'id' => '41',
            //     'periode' => '2018',
            //     'kode_akun' => '3-1700.000',
            //     'nama_akun' => 'Laba Tahun Berjalan',
            //     'nominal' => 17588089283,
            // ],
            // // Batas 41
            // [
            //     'id' => '42',
            //     'periode' => '2019',
            //     'kode_akun' => '1-1100.000',
            //     'nama_akun' => 'Kas',
            //     'nominal' => 22444707,
            // ],
            // [
            //     'id' => '43',
            //     'periode' => '2019',
            //     'kode_akun' => '1-1200.000',
            //     'nama_akun' => 'Bank',
            //     'nominal' => 9286582180,
            // ],
            // [
            //     'id' => '44',
            //     'periode' => '2019',
            //     'kode_akun' => '1-1300.000',
            //     'nama_akun' => 'Piutang Dagang',
            //     'nominal' => 61043213529,
            // ],
            // [
            //     'id' => '45',
            //     'periode' => '2019',
            //     'kode_akun' => '1-1400.000',
            //     'nama_akun' => 'Piutang Karyawan',
            //     'nominal' => 52826146,
            // ],
            // [
            //     'id' => '46',
            //     'periode' => '2019',
            //     'kode_akun' => '1-1500.000',
            //     'nama_akun' => 'Piutang Lain-lain',
            //     'nominal' => 25258595562,
            // ],
            // [
            //     'id' => '47',
            //     'periode' => '2019',
            //     'kode_akun' => '1-1600.000',
            //     'nama_akun' => 'Piutang Pemegang Saham',
            //     'nominal' => 17357499316,
            // ],
            // [
            //     'id' => '48',
            //     'periode' => '2019',
            //     'kode_akun' => '1-1700.000',
            //     'nama_akun' => 'Persediaan Barang',
            //     'nominal' => 7412870987,
            // ],
            // [
            //     'id' => '49',
            //     'periode' => '2019',
            //     'kode_akun' => '1-1800.000',
            //     'nama_akun' => 'Uang Muka & Biaya Dibayar Dimuka',
            //     'nominal' => 716829329,
            // ],
            // [
            //     'id' => '50',
            //     'periode' => '2019',
            //     'kode_akun' => '1-1900.000',
            //     'nama_akun' => 'Pajak Dibayar Dimuka',
            //     'nominal' => 1031863025,
            // ],
            // [
            //     'id' => '51',
            //     'periode' => '2019',
            //     'kode_akun' => '1-2100.000',
            //     'nama_akun' => 'Tanah',
            //     'nominal' => 55314139561,
            // ],
            // [
            //     'id' => '52',
            //     'periode' => '2019',
            //     'kode_akun' => '1-2200.000',
            //     'nama_akun' => 'Bangunan',
            //     'nominal' => 25087147669,
            // ],
            // [
            //     'id' => '53',
            //     'periode' => '2019',
            //     'kode_akun' => '1-2300.000',
            //     'nama_akun' => 'Mesin, Peralatan & Perlengkapan',
            //     'nominal' => 75114889200,
            // ],
            // [
            //     'id' => '54',
            //     'periode' => '2019',
            //     'kode_akun' => '1-2400.000',
            //     'nama_akun' => 'Kendaraan',
            //     'nominal' => 9945813857,
            // ],
            // [
            //     'id' => '55',
            //     'periode' => '2019',
            //     'kode_akun' => '1-2500.000',
            //     'nama_akun' => 'Inventaris Kantor',
            //     'nominal' => 2461562808,
            // ],
            // [
            //     'id' => '56',
            //     'periode' => '2019',
            //     'kode_akun' => '1-3100.000',
            //     'nama_akun' => 'Akum. Penyusutan Bangunan',
            //     'nominal' => -6925855100,
            // ],
            // [
            //     'id' => '57',
            //     'periode' => '2019',
            //     'kode_akun' => '1-3200.000',
            //     'nama_akun' => 'Akum. Penyusutan Mesin, Peralatan & Perlengkapan',
            //     'nominal' => -61178289012,
            // ],
            // [
            //     'id' => '58',
            //     'periode' => '2019',
            //     'kode_akun' => '1-3300.000',
            //     'nama_akun' => 'Akum. Penyusutan Kendaraan',
            //     'nominal' => -8683725152,
            // ],
            // [
            //     'id' => '59',
            //     'periode' => '2019',
            //     'kode_akun' => '1-3400.000',
            //     'nama_akun' => 'Akum. Penyusutan Inventaris Kantor',
            //     'nominal' => -2426763148,
            // ],
            // [
            //     'id' => '60',
            //     'periode' => '2019',
            //     'kode_akun' => '1-4100.000',
            //     'nama_akun' => 'Pajak Tangguhan',
            //     'nominal' => 11341409061,
            // ],
            // [
            //     'id' => '61',
            //     'periode' => '2019',
            //     'kode_akun' => '1-4200.000',
            //     'nama_akun' => 'Investasi PT.Lain',
            //     'nominal' => 38764110000,
            // ],
            // // batas 61 baris
            // [
            //     'id' => '62',
            //     'periode' => '2019',
            //     'kode_akun' => '2-1100.000',
            //     'nama_akun' => 'Hutang Dagang',
            //     'nominal' => 52841700537,
            // ],
            // [
            //     'id' => '63',
            //     'periode' => '2019',
            //     'kode_akun' => '2-1200.000',
            //     'nama_akun' => 'Hutang Komisi Penjualan',
            //     'nominal' => 1664595630,
            // ],
            // [
            //     'id' => '64',
            //     'periode' => '2019',
            //     'kode_akun' => '2-1300.000',
            //     'nama_akun' => 'Hutang Lain-lain',
            //     'nominal' => 1623430000,
            // ],
            // [
            //     'id' => '65',
            //     'periode' => '2019',
            //     'kode_akun' => '2-1400.000',
            //     'nama_akun' => 'Hutang Bank Jangka Pendek',
            //     'nominal' => 47258225107,
            // ],
            // // [
            // //     'periode' => '2019',
            // //     'kode_akun' => '501',
            // //     'nama_akun' => 'Pendapatan Penjualan',
            // //     'nominal' => 20000000,
            // // ],
            // [
            //     'id' => '66',
            //     'periode' => '2019',
            //     'kode_akun' => '2-1500.000',
            //     'nama_akun' => 'Hutang Pajak',
            //     'nominal' => 672020693,
            // ],
            // [
            //     'id' => '67',
            //     'periode' => '2019',
            //     'kode_akun' => '2-1600.000',
            //     'nama_akun' => 'Liabilitas Pembiayaan Konsumen Jangka Pendek',
            //     'nominal' => 342192435,
            // ],
            // [
            //     'id' => '68',
            //     'periode' => '2019',
            //     'kode_akun' => '2-1700.000',
            //     'nama_akun' => 'Hutang Mesin',
            //     'nominal' => 494347255,
            // ],
            // [
            //     'id' => '69',
            //     'periode' => '2019',
            //     'kode_akun' => '2-1800.000',
            //     'nama_akun' => 'Uang Muka Penjualan',
            //     'nominal' => 1540000000,
            // ],
            // [
            //     'id' => '70',
            //     'periode' => '2019',
            //     'kode_akun' => '2-1900.000',
            //     'nama_akun' => 'Biaya yang masih harus dibayar',
            //     'nominal' => 2551921928,
            // ],
            // [
            //     'id' => '71',
            //     'periode' => '2019',
            //     'kode_akun' => '2-2000.000',
            //     'nama_akun' => 'Hutang Kepada Pemegang Saham',
            //     'nominal' => 21445619441,
            // ],
            // [
            //     'id' => '72',
            //     'periode' => '2019',
            //     'kode_akun' => '2-2100.000',
            //     'nama_akun' => 'Hutang Bank Jangka Panjang',
            //     'nominal' => 61021859434,
            // ],
            // [
            //     'id' => '73',
            //     'periode' => '2019',
            //     'kode_akun' => '2-2200.000',
            //     'nama_akun' => 'Liabilitas Pembiayaan Konsumen Jangka Panjang',
            //     'nominal' => 512056438,
            // ],
            // [
            //     'id' => '74',
            //     'periode' => '2019',
            //     'kode_akun' => '2-2300.000',
            //     'nama_akun' => 'Liabilitas Imbalan Kerja',
            //     'nominal' => 11329377018,
            // ],
            // [
            //     'id' => '75',
            //     'periode' => '2019',
            //     'kode_akun' => '3-1100.000',
            //     'nama_akun' => 'Modal Disetor',
            //     'nominal' => 2500000000,
            // ],
            // [
            //     'id' => '76',
            //     'periode' => '2019',
            //     'kode_akun' => '3-1200.000',
            //     'nama_akun' => 'Uang Muka Setoran Modal',
            //     'nominal' => 0,
            // ],
            // [
            //     'id' => '77',
            //     'periode' => '2019',
            //     'kode_akun' => '3-1300.000',
            //     'nama_akun' => 'Surplus Revaluasi Tanah',
            //     'nominal' => 10700961900,
            // ],
            // [
            //     'id' => '78',
            //     'periode' => '2019',
            //     'kode_akun' => '3-1400.000',
            //     'nama_akun' => 'Tax Amnesty',
            //     'nominal' => 1620000000,
            // ],
            // [
            //     'id' => '79',
            //     'periode' => '2019',
            //     'kode_akun' => '3-1500.000',
            //     'nama_akun' => 'Laba Ditahan',
            //     'nominal' => 22338089283,
            // ],
            // [
            //     'id' => '80',
            //     'periode' => '2019',
            //     'kode_akun' => '3-1600.000',
            //     'nama_akun' => 'Deviden',
            //     'nominal' => 0,
            // ],
            // [
            //     'id' => '81',
            //     'periode' => '2019',
            //     'kode_akun' => '3-1700.000',
            //     'nama_akun' => 'Laba Tahun Berjalan',
            //     'nominal' => 20540767423,
            // ],
            // Batas 81
        ];
        Neraca::insert($neraca);
    }
}
